/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canchas;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author Antonio Zapet
 */
public class Canchas extends javax.swing.JFrame {


    /**
     * Creates new form CanchaC01
     */
    public Canchas() {
        initComponents();
        this.setLocationRelativeTo(null);
        escalarImagenLabel(lblPelota, "/imagenes/pelota.png");
        escalarImagenLabel(lblPelota1, "/imagenes/pelota.png");
        escalarImagenLabel(lblPelota2, "/imagenes/pelota.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CanchaC03 = new javax.swing.JRadioButton();
        CanchaC02 = new javax.swing.JRadioButton();
        CanchaC01 = new javax.swing.JRadioButton();
        lblPelota2 = new javax.swing.JLabel();
        lblPelota1 = new javax.swing.JLabel();
        lblPelota = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(CanchaC03);
        CanchaC03.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        CanchaC03.setForeground(new java.awt.Color(255, 255, 255));
        CanchaC03.setText("Cancha C03");
        jPanel1.add(CanchaC03, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, 250, -1));

        buttonGroup1.add(CanchaC02);
        CanchaC02.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        CanchaC02.setForeground(new java.awt.Color(255, 255, 255));
        CanchaC02.setText("Cancha C02");
        CanchaC02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanchaC02ActionPerformed(evt);
            }
        });
        jPanel1.add(CanchaC02, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 250, -1));

        buttonGroup1.add(CanchaC01);
        CanchaC01.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        CanchaC01.setForeground(new java.awt.Color(255, 255, 255));
        CanchaC01.setText("Cancha C01");
        jPanel1.add(CanchaC01, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 250, -1));

        lblPelota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pelota.png"))); // NOI18N
        jPanel1.add(lblPelota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 270, 250));

        lblPelota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pelota.png"))); // NOI18N
        jPanel1.add(lblPelota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 270, 250));

        lblPelota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pelota.png"))); // NOI18N
        jPanel1.add(lblPelota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 250));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Canchas disponibles para reservar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 770, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canchaUsuario.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -5, 1290, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CanchaC02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanchaC02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanchaC02ActionPerformed
    private void escalarImagenLabel(JLabel label, String rutaImagen) {
    // 1. Cargar la imagen desde el paquete de tu proyecto
    ImageIcon iconOriginal = new ImageIcon(getClass().getResource(rutaImagen));
    
    // 2. Escalar la imagen al ancho y alto actual del JLabel
    Image imagenEscalada = iconOriginal.getImage().getScaledInstance(
        label.getWidth(), 
        label.getHeight(), 
        Image.SCALE_SMOOTH // Mantiene la máxima calidad
    );
    
    // 3. Asignar la nueva imagen redimensionada al JLabel
    label.setIcon(new ImageIcon(imagenEscalada));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canchas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canchas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canchas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canchas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canchas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CanchaC01;
    private javax.swing.JRadioButton CanchaC02;
    private javax.swing.JRadioButton CanchaC03;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPelota;
    private javax.swing.JLabel lblPelota1;
    private javax.swing.JLabel lblPelota2;
    // End of variables declaration//GEN-END:variables
}
